# Site settings
name: Imaginate Psi
title: Imaginate Psi | Atención de la Salud Mental
description: Espacio de atención psicológica integral. Terapias y herramientas para sentirse mejor.
url: /
baseurl: ''
email: 
developer: Facundo Troitero
developer_url: https://mrfacundo.github.io
cover: https://imaginatepsi.com.ar/img/og.png
logo: https://imaginatepsi.com.ar/img/favicon-512x512.png
social:
  - title: email
    url: mailto:imaginatepsi@gmail.com
    image: social/mail
  - title: whatsapp
    url: https://wa.me/5491166140304
    image: social/whatsapp
  - title: instagram
    url: https://www.instagram.com/imaginate.psi/
    image: social/instagram


# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap

picture:
  source: img/
  output: resized_images/
  suppress_warnings: true