- text: ¿En qué nos especializamos? Tratamientos con Adolescentes, jóvenes, adultos, familia y
  orientación a padres. Algunos motivos que conducen a la consulta':''
- text: Cuando tenés un problema que, por más vueltas que le des, no podés resolverlo solo. Ya le preguntaste a tu amigo, al médico, a distintas personas y el problema sigue estando.
- text: Cuando sentís opresión en el pecho, dolor de estómago, quizás estás transitando un momento de angustia.
- text: Si no podés focalizar una idea y no te podes concentrar porque estás disperso, quizás estás en un momento de ansiedad.
- text: Si no podés dormir.
- text: Si te sentís solo o te aislás.
- text: Cuando se te presentan ideas que no te permiten accionar y hacer lo que querés y terminás congelado, a veces son obsesiones que no te dejan avanzar.
- text: Cuando estás todo el tiempo enojado e irritado y no sabes por qué.
- text: Ese es el momento de consultarnos.
